# Generated by Django 3.1.5 on 2021-07-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('published_date', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=100)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
    ]
