# Generated by Django 3.1.5 on 2021-07-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
