# Generated by Django 3.1.5 on 2021-07-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_education'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name_plural': 'AboutMe'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name_plural': 'Education'},
        ),
        migrations.AddField(
            model_name='aboutme',
            name='address',
            field=models.CharField(default='UnAvailable', max_length=200),
        ),
    ]
