# Generated by Django 3.1.5 on 2021-07-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='phone_no',
            field=models.CharField(default='UnAvailable', max_length=15),
        ),
    ]
