# Generated by Django 3.1.5 on 2021-07-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_blog_img_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='photo',
            field=models.ImageField(null=True, upload_to='profile_photo'),
        ),
    ]
