# Generated by Django 3.1.5 on 2021-07-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_auto_20210724_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='certification',
            field=models.FileField(null=True, upload_to='certification'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='cv',
            field=models.FileField(null=True, upload_to='cv'),
        ),
    ]
