# Generated by Django 3.1.5 on 2021-07-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_auto_20210724_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='cv',
            new_name='resume',
        ),
    ]
