# Generated by Django 3.1.5 on 2021-07-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='introduction',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
