# Generated by Django 3.1.5 on 2021-07-24 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_skill_introduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='introduction',
        ),
    ]
